# Generated by Django 3.0.3 on 2020-02-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio_track',
        ),
        migrations.AddField(
            model_name='audio',
            name='track',
            field=models.FileField(blank=True, null=True, upload_to='tracks'),
        ),
    ]
