# Generated by Django 3.0.3 on 2020-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_auto_20200216_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='track',
        ),
        migrations.AddField(
            model_name='audio',
            name='path',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
