# Generated by Django 3.0.3 on 2020-02-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_auto_20200216_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
